- hosts: gitlab_runner, docker
  remote_user: centos
  tasks:
  - name: Authorize Jelai's public keys.
    authorized_key:
      user: centos
      state: present
      key: "{{ lookup('file', 'jelai.keys') }}"
- hosts: docker
  remote_user: centos
  tasks:
  - name: Authorize Liam's public keys.
    authorized_key:
      user: centos
      state: present
      key: "{{ lookup('file', 'liam.keys') }}"
  - name: Authorize Curtis' public keys.
    authorized_key:
      user: centos
      state: present
      key: "{{ lookup('file', 'curtis.keys') }}"
